version: "3.3"

services:
  app-database:
    image: postgres
    restart: always
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: appuser
      POSTGRES_DB: TaskManagment
    ports:
      - 5432:5432
  
  flyway:
    image: flyway/flyway
    command: migrate
    volumes:
      - ./db:/flyway/sql
      - ./db:/flyway/conf
    depends_on:
      - app-database

  api:
    image: atanasls/task-managment-api:staging
    depends_on:
      - app-database
    ports:
      - 5001:8080
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  frontend:
    image: atanasls/task-managment-frontend:staging
    depends_on:
      - api
    ports:
      - 5002:80
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
      image: containrrr/watchtower
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      command: --debug --http-api-update
      environment:
        - WATCHTOWER_HTTP_API_TOKEN=mytoken
        - WATCHTOWER_LABEL_ENABLE=true
      labels:
        - "com.centurylinklabs.watchtower.enable=false"
      ports:
        - 8081:8080